/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPlayer,
  IPlayerInterface,
} from "../../../../contracts/interfaces/tokens/IPlayer";

const _abi = [
  {
    inputs: [],
    name: "MultiplePlayersNotAllowed",
    type: "error",
  },
] as const;

export class IPlayer__factory {
  static readonly abi = _abi;
  static createInterface(): IPlayerInterface {
    return new utils.Interface(_abi) as IPlayerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPlayer {
    return new Contract(address, _abi, signerOrProvider) as IPlayer;
  }
}
