/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGuildRegistry,
  IGuildRegistryInterface,
} from "../../../contracts/interfaces/IGuildRegistry";

const _abi = [
  {
    inputs: [],
    name: "GuildAlreadyExists",
    type: "error",
  },
  {
    inputs: [],
    name: "GuildAlreadyRegistered",
    type: "error",
  },
  {
    inputs: [],
    name: "OnlyAllowedForGuilds",
    type: "error",
  },
] as const;

export class IGuildRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IGuildRegistryInterface {
    return new utils.Interface(_abi) as IGuildRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGuildRegistry {
    return new Contract(address, _abi, signerOrProvider) as IGuildRegistry;
  }
}
