/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGuild,
  IGuildInterface,
} from "../../../contracts/interfaces/IGuild";

const _abi = [
  {
    inputs: [],
    name: "CandidateNotFound",
    type: "error",
  },
  {
    inputs: [],
    name: "NotAMember",
    type: "error",
  },
  {
    inputs: [],
    name: "Unauthorized",
    type: "error",
  },
] as const;

export class IGuild__factory {
  static readonly abi = _abi;
  static createInterface(): IGuildInterface {
    return new utils.Interface(_abi) as IGuildInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IGuild {
    return new Contract(address, _abi, signerOrProvider) as IGuild;
  }
}
