/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IManaReserve,
  IManaReserveInterface,
} from "../../../contracts/interfaces/IManaReserve";

const _abi = [
  {
    inputs: [],
    name: "WorldNotConnected",
    type: "error",
  },
] as const;

export class IManaReserve__factory {
  static readonly abi = _abi;
  static createInterface(): IManaReserveInterface {
    return new utils.Interface(_abi) as IManaReserveInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IManaReserve {
    return new Contract(address, _abi, signerOrProvider) as IManaReserve;
  }
}
