/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IManaReserve__factory } from "./IManaReserve__factory";
export { IPlayer__factory } from "./IPlayer__factory";
export { IWorld__factory } from "./IWorld__factory";
