/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tokens from "./tokens";
export type { tokens };
export type { IGuild } from "./IGuild";
export type { IGuildRegistry } from "./IGuildRegistry";
export type { IManaReserve } from "./IManaReserve";
export type { IPlayer } from "./IPlayer";
export type { IWorld } from "./IWorld";
