/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  UintArrayUtils,
  UintArrayUtilsInterface,
} from "../../../../contracts/libraries/ArrayUtils.sol/UintArrayUtils";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "array",
        type: "uint256[]",
      },
      {
        internalType: "uint256",
        name: "n",
        type: "uint256",
      },
    ],
    name: "contains",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x61035f610053600b82828239805160001a607314610046577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100355760003560e01c8063b32b8e2c1461003a575b600080fd5b610054600480360381019061004f9190610268565b61006a565b60405161006191906102df565b60405180910390f35b600080600090505b83518110156100b95782848280600101935081518110610095576100946102fa565b5b6020026020010151036100ac5760019150506100bf565b8080600101915050610072565b50600090505b92915050565b6000604051905090565b600080fd5b600080fd5b600080fd5b6000601f19601f8301169050919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fd5b610127826100de565b810181811067ffffffffffffffff82111715610146576101456100ef565b5b80604052505050565b60006101596100c5565b9050610165828261011e565b919050565b600067ffffffffffffffff821115610185576101846100ef565b5b602082029050602081019050919050565b600080fd5b6000819050919050565b6101ae8161019b565b81146101b957600080fd5b50565b6000813590506101cb816101a5565b92915050565b60006101e46101df8461016a565b61014f565b9050808382526020820190506020840283018581111561020757610206610196565b5b835b81811015610230578061021c88826101bc565b845260208401935050602081019050610209565b5050509392505050565b600082601f83011261024f5761024e6100d9565b5b813561025f8482602086016101d1565b91505092915050565b6000806040838503121561027f5761027e6100cf565b5b600083013567ffffffffffffffff81111561029d5761029c6100d4565b5b6102a98582860161023a565b92505060206102ba858286016101bc565b9150509250929050565b60008115159050919050565b6102d9816102c4565b82525050565b60006020820190506102f460008301846102d0565b92915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052603260045260246000fdfea26469706673582212203895c0b4f0c136b15355972afb0bf6fb7450a520f63713a14e4bc539e0c2cf8064736f6c63430008110033";

type UintArrayUtilsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: UintArrayUtilsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class UintArrayUtils__factory extends ContractFactory {
  constructor(...args: UintArrayUtilsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<UintArrayUtils> {
    return super.deploy(overrides || {}) as Promise<UintArrayUtils>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): UintArrayUtils {
    return super.attach(address) as UintArrayUtils;
  }
  override connect(signer: Signer): UintArrayUtils__factory {
    return super.connect(signer) as UintArrayUtils__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UintArrayUtilsInterface {
    return new utils.Interface(_abi) as UintArrayUtilsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UintArrayUtils {
    return new Contract(address, _abi, signerOrProvider) as UintArrayUtils;
  }
}
